import time

def playExitlude():
    print("We hope you enjoyed your stay")
    time.sleep(6)
    print("It's good to have you with us, even if it's just for the day")
    time.sleep(10)
    print("We hope you enjoyed your stay")
    time.sleep(5)
    print("Outside the sun is shining, seems like heaven ain't far away")
    time.sleep(8)
    print("It's good to have you with us")
    time.sleep(3)
    print("Even if it's just for the day\n")
    time.sleep(19)
    #time.sleep(10)

    #time.sleep(5)
    print("Aggressively we all defend the role we play")
    time.sleep(6.5)
    print("Regrettably time's come to send you on your way")
    time.sleep(7.5)
    print("We’ve seen it all bonfires of trust flash floods of pain")
    time.sleep(7.5)
    print("It doesn't really matter, don't you worry, it'll all work out")
    time.sleep(7.2)
    print("No, it doesn't even matter, don't you worry 'bout what it's all about\n")
    time.sleep(7)

    print("We hope you enjoyed your stay")
    time.sleep(5.3)
    print("It's good to have you with us")
    time.sleep(5)
    print("Even if it's just for the day\n")
    time.sleep(3)
    print("We hope you enjoyed your stay")
    time.sleep(5)
    print("Outside the sun is shining, seems like heaven ain't far away")
    time.sleep(8)
    print("It's good to have you with us")
    time.sleep(15)
    print("Even if it's just for the day\n")

def playOcean():
    print("Ocean man, take me by the hand, lead me to the land")
    time.sleep(6.8)
    print("That you understand")
    time.sleep(3)
    print("Ocean man, the voyage to the corner of the globe")
    time.sleep(4.3)
    print("Is a real trip\n")
    time.sleep(3.2)

    print("Ocean man, the crust of a tan man imbibed by the sand")
    time.sleep(5)
    print("Soaking up the thirst of the land\n")
    time.sleep(3)

    print("Ocean man, can you see through the wonder of amazement")
    time.sleep(4.5)
    print("At the Oberman?")
    time.sleep(2.6)
    print("Ocean man, the crust is elusive when it casts forth")
    time.sleep(5.6)
    print("To the childlike man")
    time.sleep(2.8)
    print("Ocean man, the sequence of a life form braised in the sand")
    time.sleep(5)
    print("Soaking up the thirst of the land\n")
    time.sleep(3)

    print("Ocean man")
    time.sleep(8)
    print("Ocean man")
    time.sleep(7)
    print("Ocean man\n")
    time.sleep(9)

    print("Ocean man, take me by the hand, lead me to the land")
    time.sleep(4.5)
    print("That you understand")
    time.sleep(2)
    print("Ocean man, the voyage to the corner of the globe")
    time.sleep(5)
    print("Is a real trip (Trip, trip, trip, trip, trip)\n")
    time.sleep(4)

    print("Ocean man, the crust of a tan man imbibed by the sand")
    time.sleep(5)
    print("Soaking up the thirst of the land\n")
    time.sleep(3)

    print("Ocean man, can you see through the wonder of amazement")
    time.sleep(5)
    print("At the Oberman?")
    time.sleep(2.5)
    print("Ocean man, the crust is elusive when it casts forth")
    time.sleep(5)
    print("To the childlike man\n")
    time.sleep(3)

    print("Ocean man, the sequence of a life form braised in the sand")
    time.sleep(5)
    print("Soaking up the thirst of the land")
    time.sleep(3)
    print("Ocean man\n")

def playRick():
    print("We're no strangers to love")
    time.sleep(22.6)
    print("You know the rules and so do I")
    time.sleep(4.6)
    print("A full commitment's what I'm thinking of")
    time.sleep(4.2)
    print("You wouldn't get this from any other guy")
    time.sleep(3.7)
    print("\n")

    print("I just wanna tell you how I'm feeling")
    time.sleep(4.7)
    print("Gotta make you understand")
    time.sleep(3.8)
    print("\n")

    print("Never gonna give you up")
    time.sleep(1.8)
    print("Never gonna let you down")
    time.sleep(2.2)
    print("Never gonna run around and desert you")
    time.sleep(4.3)
    print("Never gonna make you cry")
    time.sleep(2.1)
    print("Never gonna say goodbye")
    time.sleep(1.9)
    print("Never gonna tell a lie and hurt you")
    time.sleep(3.9)
    print("\n")

    print("We've known each other for so long")
    time.sleep(5.2)
    print("Your heart's been aching, but you're too shy to say it")
    time.sleep(4.35)
    print("Inside, we both know what's been going on")
    time.sleep(4)
    print("We know the game, and we're gonna play it")
    time.sleep(4.4)
    print("\n")

    print("And if you ask me how I'm feeling")
    time.sleep(4.8)
    print("Don't tell me you're too blind to see")
    time.sleep(3)
    print("\n")

    print("Never gonna give you up")
    time.sleep(2)
    print("Never gonna let you down")
    time.sleep(2.3)
    print("Never gonna run around and desert you")
    time.sleep(3.8)
    print("Never gonna make you cry")
    time.sleep(2.5)
    print("Never gonna say goodbye")
    time.sleep(2)
    print("Never gonna tell a lie and hurt you")
    time.sleep(4)
    print("Never gonna give you up")
    time.sleep(2.4)
    print("Never gonna let you down")
    time.sleep(2.1)
    print("Never gonna run around and desert you")
    time.sleep(4)
    print("Never gonna make you cry")
    time.sleep(2.2)
    print("Never gonna say goodbye")
    time.sleep(2)
    print("Never gonna tell a lie and hurt you")
    time.sleep(4.7)
    print("\n")

    print("Ooh (Give you up)")
    time.sleep(3.6)
    print("Ooh-ooh (Give you up)")
    time.sleep(4.3)
    print("Ooh-ooh")
    print("Never gonna give, never gonna give (Give you up)")
    time.sleep(4.2)
    print("Ooh-ooh")
    print("Never gonna give, never gonna give (Give you up)")
    time.sleep(4.3)
    print("\n")

    print("We've known each other for so long")
    time.sleep(4.2)
    print("Your heart's been aching, but you're too shy to say it")
    time.sleep(5)
    print("Inside, we both know what's been going on")
    time.sleep(4.2)
    print("We know the game, and we're gonna play it")
    time.sleep(4.2)
    print("\n")

    print("I just wanna tell you how I'm feeling")
    time.sleep(4)
    print("Gotta make you understand")
    time.sleep(4)
    print("\n")

    print("Never gonna give you up")
    time.sleep(3)
    print("Never gonna let you down")
    time.sleep(2)
    print("Never gonna run around and desert you")
    time.sleep(3.9)
    print("Never gonna make you cry")
    time.sleep(2.2)
    print("Never gonna say goodbye")
    time.sleep(2.1)
    print("Never gonna tell a lie and hurt you")
    time.sleep(4)
    print("Never gonna give you up")
    time.sleep(2.2)
    print("Never gonna let you down")
    time.sleep(2.1)
    print("Never gonna run around and desert you")
    time.sleep(4)
    print("Never gonna make you cry")
    time.sleep(2.5)
    print("Never gonna say goodbye")
    time.sleep(2)
    print("Never gonna tell a lie and hurt you")
    time.sleep(4)
    print("Never gonna give you up")
    time.sleep(2)
    print("Never gonna let you down")
    time.sleep(2)
    print("Never gonna run around and desert you")
    time.sleep(4)
    print("Never gonna make you cry")
    time.sleep(2)
    print("Never gonna say goodbye")
    time.sleep(2)
    print("Never gonna tell a lie and hurt you")

def playCountry():
    print("Almost heaven, West Virginia, Blue Ridge Mountains, Shenandoah River")
    time.sleep(19.5)
    print("Life is old there, older than the trees, younger than the mountains, blowing like a breeze")
    time.sleep(10.5)
    print("\n")

    print("Country roads, take me home to the place I belong")
    time.sleep(12.1)
    print("West Virginia, mountain mamma, take me home, country roads")
    time.sleep(12.5)
    print("\n")

    print("All my memories gather round her, miner's lady, stranger to blue water")
    time.sleep(13.8)
    print("Dark and dusty, painted on the sky, misty taste of moonshine, teardrop in my eye")
    time.sleep(9.9)
    print("\n")

    print("Country roads, take me home to the place I belong")
    time.sleep(11.7)
    print("West Virginia, mountain mamma, take me home, country roads")  
    time.sleep(12.8)
    print("\n")

    print("I hear her voice in the morning hour, she calls me, the radio reminds me of my home far away")
    time.sleep(10.1)
    print("And driving down the road I get a feeling that I should have been home yesterday, yesterday")
    time.sleep(11.5)
    print("\n")

    print("Country roads, take me home to the place I belong")
    time.sleep(12)
    print("West Virginia, mountain mamma, take me home, country roads")
    time.sleep(11.6)
    print("\n")

    print("Country roads, take me home to the place I belong")
    time.sleep(11.5)
    print("West Virginia, mountain mamma, take me home, country roads")
    time.sleep(10)
    print("\n")

    print("Take me home, down country roads")
    time.sleep(6)
    print("Take me home, down country roads")

def playLoseYourself():
    time.sleep(33)
    print("Look, if you had one shot, or one opportunity")
    time.sleep(10)
    print("To seize everything you ever wanted, in one moment")
    time.sleep(5)
    print("Would you capture it, or just let it slip?")
    time.sleep(4)
    print("\n")
    
    print("Yo! His palms are sweaty, knees weak, arms are heavy")
    time.sleep(3.5)
    print("There's vomit on his sweater already: Mom's spaghetti")
    time.sleep(3.2)
    print("He's nervous, but on the surface he looks calm and ready")
    time.sleep(2.7)
    print("To drop bombs, but he keeps on forgetting")
    time.sleep(2.7)
    print("What he wrote down, the whole crowd goes so loud")
    time.sleep(2.7)
    print("He opens his mouth, but the words won't come out")
    time.sleep(2.7)
    print("He's choking, how? Everybody's joking now")
    time.sleep(2.8)
    print("The clock's run out, time's up, over, blaow!")
    time.sleep(2.8)
    print("Snap back to reality, ope there goes gravity, ope")
    time.sleep(3)
    print("There goes Rabbit, he choked, he's so mad but he won't")
    time.sleep(3)
    print("Give up that easy, no, he won't have it, he knows")
    time.sleep(3)
    print("His whole back's to these ropes, it don't matter, he's dope")
    time.sleep(3.6)
    print("He knows that but he's broke, he's so stagnant, he knows")
    time.sleep(2.2)
    print("When he goes back to this mobile home, that's when it's")
    time.sleep(2.9)
    print("Back to the lab again yo, this whole rhapsody")
    time.sleep(3.4)
    print("Better go capture this moment and hope it don't pass him, and")
    time.sleep(2)
    print("\n")

    print("You better lose yourself in the music")
    time.sleep(2.5)
    print("The moment, you own it, you better never let it go")
    time.sleep(2.2)
    print("You only get one shot, do not miss your chance to blow")
    time.sleep(2.6)
    print("This opportunity comes once in a lifetime, yo")
    time.sleep(3.2)
    print("You better lose yourself in the music")
    time.sleep(3.2)
    print("The moment, you own it, you better never let it go")
    time.sleep(2.4)
    print("You only get one shot, do not miss your chance to blow")
    time.sleep(2.7)
    print("This opportunity comes once in a lifetime, yo")
    time.sleep(2.7)
    print("You better…")
    time.sleep(0.7)
    print("\n")

    print("His soul's escaping through this hole that is gaping")
    time.sleep(2.7)
    print("This world is mine for the taking, make me king")
    time.sleep(2.8)
    print("As we move toward a New World Order")
    time.sleep(3.2)
    print("A normal life is boring; but superstardom's")
    time.sleep(2.3)
    print("Close to post-mortem, it only grows harder")
    time.sleep(2.8)
    print("Homie grows hotter, he blows, it's all over")
    time.sleep(2.6)
    print("These hoes is all on him, coast-to-coast shows")
    time.sleep(2.7)
    print("He's known as the Globetrotter, lonely roads")
    time.sleep(2.6)
    print("God only knows, he's grown farther from home, he's no father")
    time.sleep(2.8)
    print("He goes home and barely knows his own daughter")
    time.sleep(2.6)
    print("But hold your nose, 'cause here goes the cold water")
    time.sleep(2.7)
    print("These hoes don't want him no mo', he's cold product")
    time.sleep(2.5)
    print("They moved on to the next schmoe who flows")
    time.sleep(2.5)
    print("He nose-dove and sold nada, and so the soap opera")
    time.sleep(3)
    print("Is told, it unfolds, I suppose it's old, partner")
    time.sleep(2.6)
    print("But the beat goes on: da da dum da dum da da da da")
    time.sleep(3)
    print("\n")

    print("You better lose yourself in the music")
    time.sleep(2.5)
    print("The moment, you own it, you better never let it go")
    time.sleep(2.1)
    print("You only get one shot, do not miss your chance to blow")
    time.sleep(2.6)
    print("This opportunity comes once in a lifetime, yo")
    time.sleep(2.8)
    print("You better lose yourself in the music")
    time.sleep(2.8)
    print("The moment, you own it, you better never let it go")
    time.sleep(3)
    print("You only get one shot, do not miss your chance to blow")
    time.sleep(3)
    print("This opportunity comes once in a lifetime, yo")
    time.sleep(2.6)
    print("You better…")
    print("\n")

    print("No more games, I'ma change what you call rage")
    time.sleep(2.9)
    print("Tear this motherfuckin' roof off like two dogs caged")
    time.sleep(2.8)
    print("I was playin' in the beginning, the mood all changed")
    time.sleep(2.7)
    print("I've been chewed up and spit out and booed off stage")
    time.sleep(2.7)
    print("But I kept rhymin' and stepped right in the next cypher")
    time.sleep(2.8)
    print("Best believe somebody's payin' the Pied Piper")
    time.sleep(2.5)
    print("All the pain inside amplified by the")
    time.sleep(2.6)
    print("Fact that I can't get by with my 9-to-5")
    time.sleep(2.5)
    print("And I can't provide the right type of life for my family")
    time.sleep(2.4)
    print("'Cause man, these goddamn food stamps don't buy diapers")
    time.sleep(2.5)
    print("And there's no movie, there's no Mekhi Phifer, this is my life")
    time.sleep(3.2)
    print("And these times are so hard, and it's gettin' even harder")
    time.sleep(2.2)
    print("Tryna feed and water my seed, plus teeter-totter")
    time.sleep(2.4)
    print("Caught up between bein' a father and a prima donna")
    time.sleep(2)
    print("Baby mama drama, screamin' on her, too much for me to wanna")
    time.sleep(2.4)
    print("Stay in one spot, another day of monotony's")
    time.sleep(2.2)
    print("Gotten me to the point I'm like a snail, I've got")
    time.sleep(2.1)
    print("To formulate a plot or end up in jail or shot")
    time.sleep(2.1)
    print("Success is my only motherfuckin' option, failure's not")
    time.sleep(2.5)
    print("Mom, I love you, but this trailer's got")
    time.sleep(2.2)
    print("To go; I cannot grow old in Salem's Lot")
    time.sleep(2.2)
    print("So here I go, it's my shot: feet, fail me not")
    time.sleep(2.2)
    print("This may be the only opportunity that I got")
    print("\n")

    print("You better lose yourself in the music")
    time.sleep(2.5)
    print("The moment, you own it, you better never let it go (go)")
    time.sleep(2)
    print("You only get one shot, do not miss your chance to blow")
    time.sleep(2.5)
    print("This opportunity comes once in a lifetime, yo")
    time.sleep(2)
    print("You better lose yourself in the music")
    time.sleep(3)
    print("The moment, you own it, you better never let it go (go)")
    time.sleep(3)
    print("You only get one shot, do not miss your chance to blow")
    time.sleep(3)
    print("This opportunity comes once in a lifetime, yo")
    time.sleep(2.5)
    print("You better…")
    time.sleep(5)
    print("\n")

    print("You can do anything you set your mind to, man")

